name = "fripse"
compatibility_date = "2026-08-12"
workers_dev = true
preview_urls = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "www.fripse.com/*"
zone_name = "fripse.com"

[[routes]]
pattern = "fripse.com/*"
zone_name = "fripse.com"
